create index if not exists growth_drops_source_evidence_idx on public.growth_drops(source_evidence_id) where source_evidence_id is not null;
create index if not exists growth_drops_approved_by_idx on public.growth_drops(approved_by) where approved_by is not null;
create index if not exists growth_partner_attributions_partner_idx on public.growth_partner_attributions(partner_id);
create index if not exists growth_partner_attributions_profile_idx on public.growth_partner_attributions(profile_id) where profile_id is not null;
create index if not exists growth_partner_attributions_project_idx on public.growth_partner_attributions(project_id) where project_id is not null;
create index if not exists growth_time_log_group_idx on public.growth_time_log(group_id) where group_id is not null;
create index if not exists growth_time_log_project_idx on public.growth_time_log(project_id) where project_id is not null;
create index if not exists growth_time_log_partner_idx on public.growth_time_log(partner_id) where partner_id is not null;
create index if not exists growth_time_log_logged_for_idx on public.growth_time_log(logged_for desc);
create index if not exists project_evidence_library_vendor_idx on public.project_evidence_library(vendor_id) where vendor_id is not null;
create index if not exists referrals_parent_referral_idx on public.referrals(parent_referral_id) where parent_referral_id is not null;
create index if not exists referrals_source_project_idx on public.referrals(source_project_id) where source_project_id is not null;
create index if not exists vendor_bench_qualifying_project_idx on public.vendor_bench_candidates(qualifying_project_id);
create index if not exists vendor_reference_checks_vendor_idx on public.vendor_reference_checks(vendor_id);
create index if not exists project_milestone_tasks_open_idx on public.project_milestone_tasks(status,due_at,created_at) where status='open';
