alter table public.gpi_connection_requests add column if not exists seeker_profile_id uuid;
do $$ begin if not exists (select 1 from pg_constraint where conname='gpi_connection_requests_seeker_profile_id_fkey' and conrelid='public.gpi_connection_requests'::regclass) then alter table public.gpi_connection_requests add constraint gpi_connection_requests_seeker_profile_id_fkey foreign key (seeker_profile_id) references public.profiles(id) on delete restrict; end if; end $$;
create index if not exists gpi_connection_requests_seeker_profile_created_idx on public.gpi_connection_requests(seeker_profile_id, created_at desc) where seeker_profile_id is not null;
create or replace function public.gpi_lock_connection_request_seeker_identity() returns trigger language plpgsql security definer set search_path to '' as $function$ begin if tg_op='UPDATE' and new.seeker_profile_id is distinct from old.seeker_profile_id then raise exception 'Seeker profile linkage is immutable' using errcode='42501'; end if; return new; end $function$;
revoke all on function public.gpi_lock_connection_request_seeker_identity() from public, anon, authenticated; grant execute on function public.gpi_lock_connection_request_seeker_identity() to service_role;
drop trigger if exists gpi_connection_requests_05_seeker_identity_lock on public.gpi_connection_requests; create trigger gpi_connection_requests_05_seeker_identity_lock before update on public.gpi_connection_requests for each row execute function public.gpi_lock_connection_request_seeker_identity();
create or replace function public.gpi_service_submit_connection_request_v2(p_opportunity_id uuid,p_occurrence_id uuid,p_normalized_email text,p_email_fingerprint bytea,p_fingerprint_key_version smallint,p_consent_accepted boolean,p_participant_requirement_ids uuid[],p_age_range_affirmed boolean,p_process_opt_outs text[],p_seeker_profile_id uuid default null) returns table(request_id uuid, request_status text, deduplicated boolean) language plpgsql security definer set search_path to '' as $function$
declare v_request_id uuid; v_policy text; v_required integer; v_affirmed integer; v_min smallint; v_max smallint; v_bg boolean; v_orient boolean; v_apply boolean; v_member boolean; v_opt text[]:=coalesce(p_process_opt_outs,'{}'::text[]); v_req uuid[]:=coalesce(p_participant_requirement_ids,'{}'::uuid[]); v_profile_email text; v_profile_email_confirmed boolean:=false; v_endpoint uuid; v_now timestamptz:=now();
begin
if not coalesce(p_consent_accepted,false) then raise exception 'Current contact consent is required' using errcode='22023'; end if;
if p_opportunity_id is null or p_normalized_email is null or p_email_fingerprint is null or octet_length(p_email_fingerprint)<>32 or p_fingerprint_key_version is null or p_fingerprint_key_version<1 then raise exception 'Trusted submission fields are missing or invalid' using errcode='22023'; end if;
if p_normalized_email<>lower(btrim(p_normalized_email)) then raise exception 'Normalized email is required' using errcode='22023'; end if;
if p_seeker_profile_id is not null then select lower(u.email),(u.email_confirmed_at is not null) into v_profile_email,v_profile_email_confirmed from auth.users u join public.profiles p on p.id=u.id where u.id=p_seeker_profile_id; if not found or not v_profile_email_confirmed or v_profile_email is distinct from p_normalized_email then raise exception 'Authenticated seeker identity does not match the confirmed FaithBid email' using errcode='42501'; end if; end if;
if exists(select 1 from unnest(v_opt) o(value) where value not in ('background_check','orientation','application','membership')) then raise exception 'Unknown process requirement opt-out' using errcode='22023'; end if;
select min_age,max_age,requires_background_check,requires_orientation,requires_application,requires_membership into v_min,v_max,v_bg,v_orient,v_apply,v_member from public.gpi_opportunities where id=p_opportunity_id; if not found then raise exception 'Opportunity not found' using errcode='P0002'; end if;
if (v_bg and 'background_check'=any(v_opt)) or (v_orient and 'orientation'=any(v_opt)) or (v_apply and 'application'=any(v_opt)) or (v_member and 'membership'=any(v_opt)) then raise exception 'A required process was declined' using errcode='23514'; end if;
select count(*) into v_required from public.gpi_opportunity_participant_audiences where opportunity_id=p_opportunity_id and treatment='confirmation_required'; select count(distinct id) into v_affirmed from unnest(v_req) r(id);
if v_affirmed<>v_required or exists(select 1 from unnest(v_req) r(id) where not exists(select 1 from public.gpi_opportunity_participant_audiences a where a.id=r.id and a.opportunity_id=p_opportunity_id and a.treatment='confirmation_required')) then raise exception 'Every current participant requirement must be affirmed exactly once' using errcode='23514'; end if;
if (v_min is not null or v_max is not null) and not coalesce(p_age_range_affirmed,false) then raise exception 'Age-range affirmation is required' using errcode='23514'; end if;
select version into v_policy from public.gpi_consent_policies where active and effective_at<=v_now; if not found then raise exception 'No active contact-consent policy' using errcode='23514'; end if;
begin insert into public.gpi_connection_requests(opportunity_id,occurrence_id,seeker_profile_id,seeker_email,seeker_email_fingerprint,fingerprint_key_version,consent_policy_version,consent_given_at,verification_expires_at) values(p_opportunity_id,p_occurrence_id,p_seeker_profile_id,p_normalized_email,p_email_fingerprint,p_fingerprint_key_version,v_policy,v_now,v_now+interval '24 hours') returning id into v_request_id;
exception when unique_violation then select id into v_request_id from public.gpi_connection_requests where seeker_email_fingerprint=p_email_fingerprint and opportunity_id=p_opportunity_id and occurrence_dedupe_key=coalesce(p_occurrence_id,'00000000-0000-0000-0000-000000000001'::uuid) and status in ('pending_verification','submitted','notified','next_step_provided') order by created_at desc limit 1; if v_request_id is null then raise; end if; return query select v_request_id,(select status from public.gpi_connection_requests where id=v_request_id),true; return; end;
insert into public.gpi_connection_request_confirmations(connection_request_id,confirmation_type,participant_audience_requirement_id,prompt_snapshot) select v_request_id,'participant_audience',a.id,a.confirmation_prompt from public.gpi_opportunity_participant_audiences a where a.id=any(v_req);
if v_min is not null or v_max is not null then insert into public.gpi_connection_request_confirmations(connection_request_id,confirmation_type,age_min_snapshot,age_max_snapshot,prompt_snapshot) values(v_request_id,'age_range',v_min,v_max,'I confirm that I meet the listed age requirement.'); end if;
if p_seeker_profile_id is not null then select e.id into v_endpoint from public.gpi_opportunities o join public.gpi_organization_notification_endpoints e on e.organization_id=o.organization_id and e.is_primary and e.status='verified' where o.id=p_opportunity_id; if v_endpoint is null then raise exception 'Verified primary organization endpoint is unavailable' using errcode='23514'; end if; update public.gpi_connection_requests set status='submitted',submitted_at=v_now,contact_verified_at=v_now,notification_queued_at=v_now where id=v_request_id; insert into public.gpi_notification_deliveries(connection_request_id,organization_endpoint_id,notification_type,idempotency_key,status,next_attempt_at) values(v_request_id,v_endpoint,'org_request','org_request/'||v_request_id::text,'pending',v_now); return query select v_request_id,'submitted'::text,false; return; end if;
insert into public.gpi_notification_deliveries(connection_request_id,notification_type,idempotency_key,status,next_attempt_at) values(v_request_id,'verify_contact','verify_contact/'||v_request_id::text,'pending',v_now); return query select v_request_id,'pending_verification'::text,false;
end $function$;
revoke all on function public.gpi_service_submit_connection_request_v2(uuid,uuid,text,bytea,smallint,boolean,uuid[],boolean,text[],uuid) from public, anon, authenticated; grant execute on function public.gpi_service_submit_connection_request_v2(uuid,uuid,text,bytea,smallint,boolean,uuid[],boolean,text[],uuid) to service_role;
create or replace function public.gpi_seeker_list_my_requests(p_queue text default 'active',p_limit integer default 75) returns jsonb language plpgsql stable security definer set search_path to '' as $function$
declare v_profile_id uuid:=auth.uid(); v_queue text:=lower(btrim(coalesce(p_queue,'active'))); v_limit integer:=greatest(1,least(coalesce(p_limit,75),150)); v_requests jsonb; v_summary jsonb;
begin if v_profile_id is null then raise exception 'authentication required' using errcode='42501'; end if; if v_queue not in ('active','awaiting_host','next_step','closed','all') then raise exception 'Unknown seeker request queue' using errcode='22023'; end if;
select jsonb_build_object('active_count',count(*) filter(where q.status in ('pending_verification','submitted','notified','next_step_provided')),'awaiting_host_count',count(*) filter(where q.status in ('submitted','notified')),'next_step_count',count(*) filter(where q.status='next_step_provided'),'connected_count',count(*) filter(where q.status='seeker_confirmed'),'closed_count',count(*) filter(where q.closed_at is not null),'pending_verification_count',count(*) filter(where q.status='pending_verification')) into v_summary from public.gpi_connection_requests q where q.seeker_profile_id=v_profile_id;
select coalesce(jsonb_agg(jsonb_build_object('request_id',q.id,'status',q.status,'opportunity_id',q.opportunity_id,'opportunity_title',o.title,'organization_id',o.organization_id,'organization_name',org.name,'goal',o.goal,'schedule_type',o.schedule_type,'occurrence_id',q.occurrence_id,'occurrence_starts_at',x.starts_at,'occurrence_ends_at',x.ends_at,'created_at',q.created_at,'submitted_at',q.submitted_at,'notified_at',q.notified_at,'org_responded_at',q.org_responded_at,'next_step_provided_at',q.next_step_provided_at,'response_due_at',q.response_due_at,'outcome_due_at',q.outcome_due_at,'closed_at',q.closed_at,'close_reason',q.close_reason,'details_released',q.private_details_release_authorized_at is not null) order by q.updated_at desc,q.created_at desc),'[]'::jsonb) into v_requests from (select q.* from public.gpi_connection_requests q where q.seeker_profile_id=v_profile_id and (v_queue='all' or (v_queue='active' and q.status in ('pending_verification','submitted','notified','next_step_provided')) or (v_queue='awaiting_host' and q.status in ('submitted','notified')) or (v_queue='next_step' and q.status='next_step_provided') or (v_queue='closed' and q.closed_at is not null)) order by q.updated_at desc,q.created_at desc limit v_limit) q join public.gpi_opportunities o on o.id=q.opportunity_id join public.gpi_organizations org on org.id=o.organization_id left join public.gpi_opportunity_occurrences x on x.id=q.occurrence_id;
return jsonb_build_object('summary',coalesce(v_summary,'{}'::jsonb),'requests',coalesce(v_requests,'[]'::jsonb)); end $function$;
create or replace function public.gpi_seeker_get_request(p_request_id uuid) returns jsonb language plpgsql stable security definer set search_path to '' as $function$
declare v_profile_id uuid:=auth.uid(); v_result jsonb;
begin if v_profile_id is null then raise exception 'authentication required' using errcode='42501'; end if; select jsonb_build_object('request',jsonb_build_object('request_id',q.id,'status',q.status,'opportunity_id',q.opportunity_id,'opportunity_title',o.title,'organization_id',o.organization_id,'organization_name',org.name,'goal',o.goal,'schedule_type',o.schedule_type,'location_mode',o.location_mode,'location_visibility',o.location_visibility,'occurrence_id',q.occurrence_id,'occurrence_starts_at',x.starts_at,'occurrence_ends_at',x.ends_at,'created_at',q.created_at,'submitted_at',q.submitted_at,'notified_at',q.notified_at,'org_responded_at',q.org_responded_at,'next_step_provided_at',q.next_step_provided_at,'response_due_at',q.response_due_at,'outcome_due_at',q.outcome_due_at,'closed_at',q.closed_at,'close_reason',q.close_reason,'details_released',q.private_details_release_authorized_at is not null),'confirmations',coalesce((select jsonb_agg(jsonb_build_object('confirmation_type',c.confirmation_type,'prompt',c.prompt_snapshot,'age_min',c.age_min_snapshot,'age_max',c.age_max_snapshot) order by c.affirmed_at) from public.gpi_connection_request_confirmations c where c.connection_request_id=q.id),'[]'::jsonb),'next_step',case when q.private_details_release_authorized_at is not null then (select jsonb_build_object('instructions',n.instructions,'created_at',n.created_at,'updated_at',n.updated_at) from public.gpi_connection_request_next_steps n where n.connection_request_id=q.id) else null end,'released_details',case when q.private_details_release_authorized_at is not null then (select jsonb_build_object('private_address_text',p.private_address_text,'virtual_join_url',p.virtual_join_url) from public.gpi_opportunity_private_details p where p.opportunity_id=q.opportunity_id) else null end) into v_result from public.gpi_connection_requests q join public.gpi_opportunities o on o.id=q.opportunity_id join public.gpi_organizations org on org.id=o.organization_id left join public.gpi_opportunity_occurrences x on x.id=q.occurrence_id where q.id=p_request_id and q.seeker_profile_id=v_profile_id; if v_result is null then raise exception 'request not found or not authorized' using errcode='42501'; end if; return v_result; end $function$;
create or replace function public.gpi_seeker_report_outcome(p_request_id uuid,p_outcome text) returns jsonb language plpgsql security definer set search_path to '' as $function$
declare v_profile_id uuid:=auth.uid(); v_request public.gpi_connection_requests%rowtype; v_now timestamptz:=now();
begin if v_profile_id is null then raise exception 'authentication required' using errcode='42501'; end if; if p_outcome not in ('seeker_confirmed','seeker_did_not_connect') then raise exception 'Unknown seeker outcome' using errcode='22023'; end if; select * into v_request from public.gpi_connection_requests where id=p_request_id and seeker_profile_id=v_profile_id for update; if not found then raise exception 'request not found or not authorized' using errcode='42501'; end if; if v_request.status=p_outcome then return jsonb_build_object('request_id',v_request.id,'status',v_request.status,'deduplicated',true); end if; if v_request.status<>'next_step_provided' or v_request.outcome_due_at is null or v_request.outcome_due_at<=v_now then raise exception 'Request is no longer awaiting your outcome' using errcode='23514'; end if; update public.gpi_connection_requests set status=p_outcome,closed_at=v_now,close_reason=case p_outcome when 'seeker_confirmed' then 'seeker_confirmed_connection' else 'seeker_reported_no_connection' end,seeker_confirmed_at=case when p_outcome='seeker_confirmed' then v_now else null end where id=v_request.id; update public.gpi_action_tokens set revoked_at=v_now where connection_request_id=v_request.id and purpose='seeker_outcome' and revoked_at is null; update public.gpi_action_sessions set revoked_at=v_now where connection_request_id=v_request.id and purpose='seeker_outcome' and revoked_at is null; update public.gpi_notification_deliveries set status='failed',next_attempt_at=null,last_error_code='handled_in_workspace' where connection_request_id=v_request.id and notification_type='seeker_outcome' and status in ('pending','sending'); return jsonb_build_object('request_id',v_request.id,'status',p_outcome,'deduplicated',false); end $function$;
revoke all on function public.gpi_seeker_list_my_requests(text,integer) from public, anon; revoke all on function public.gpi_seeker_get_request(uuid) from public, anon; revoke all on function public.gpi_seeker_report_outcome(uuid,text) from public, anon; grant execute on function public.gpi_seeker_list_my_requests(text,integer) to authenticated, service_role; grant execute on function public.gpi_seeker_get_request(uuid) to authenticated, service_role; grant execute on function public.gpi_seeker_report_outcome(uuid,text) to authenticated, service_role;
